### ISSUE TITLE
PineFlip?

### ISSUE THREAD

**Issue by ColossusYTTV** [pixel773/MonkeGoRoll#1]
Wow. You really skidded the EXACT code from my mod PineFlip that was made for: https://www.youtube.com/@PineVr/featured and posted it in the official modding discord. Nice

**Comment by pixel773** [comment]
Hello, I know that it seems that I stole your code but its an idea that came to mind. I don't know who you are or that pine even had a mod like this but its the only way to make a rigid body roll.

**Comment by pixel773** [comment]
I also see that you are a cheater, I think you are just trying to fake and get me to delete the mod.

**Comment by ColossusYTTV** [comment]
I know there is nothing he reset his youtube videos recently. Ask him yourself if you must. Also its rich that your calling me a cheater after you copied my mod, doesnt that make you a cheater too

**Comment by pixel773** [comment]
do you even know what "cheating" is?

I don't cheat, cheating is using an unfair advantage in public games. I don't use that and in your profile you legit made a mod menu

also how would I steal your code if its not publicly available? hmm?

**Comment by ColossusYTTV** [comment]
It is publically available.. it's in my discord and linked in many other
discords.
